events {}

http {

    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    client_max_body_size 100M;

    upstream django {
        server backend:8000;
    }

    # Redirigir todo HTTP → HTTPS
    server {
        listen 80;
        server_name 10.75.0.225;
        return 301 https://$host$request_uri;
    }

    # Servidor HTTPS
    server {
        listen 443 ssl;
        server_name 10.75.0.225;

        # Certificados
        ssl_certificate     /etc/nginx/ssl/vortexsql.crt;
        ssl_certificate_key /etc/nginx/ssl/vortexsql.key;

        # Protocolos seguros (deshabilitar TLS 1.0 y 1.1)
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;

        location /static/ {
            alias /static/;
        }

        location /media/ {
            alias /media/;
        }

        location / {
            proxy_pass http://django;

            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}