# Generated by Django 6.0.5 on 2026-05-12 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='actualizaciones',
            fields=[
                ('id_actualizaciones', models.AutoField(primary_key=True, serialize=False)),
                ('major_version', models.CharField(max_length=50)),
                ('cu', models.CharField(max_length=100)),
                ('kb', models.CharField(max_length=100)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('soportado', models.BooleanField(default=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'actualizaciones',
            },
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField()),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='instancia',
            fields=[
                ('id_instancia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_instancia', models.CharField(max_length=255)),
                ('puerto', models.IntegerField()),
                ('major_version', models.CharField(max_length=50)),
                ('edition', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'instancia',
            },
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='conexion',
            fields=[
                ('id_conexion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_autenticacion', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=255)),
                ('password_encriptado', models.CharField(max_length=512)),
                ('instancia', models.ForeignKey(db_column='instancia_id', on_delete=django.db.models.deletion.CASCADE, to='sgbda.instancia')),
            ],
            options={
                'db_table': 'conexion',
            },
        ),
        migrations.CreateModel(
            name='checkSQL',
            fields=[
                ('id_check', models.AutoField(primary_key=True, serialize=False)),
                ('build_detectado', models.CharField(max_length=100)),
                ('build_referencia', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('fecha_check', models.DateTimeField()),
                ('detalle', models.TextField(blank=True, null=True)),
                ('instancia', models.ForeignKey(db_column='instancia_id', on_delete=django.db.models.deletion.CASCADE, to='sgbda.instancia')),
            ],
            options={
                'db_table': 'check_sql',
            },
        ),
        migrations.CreateModel(
            name='servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=255)),
                ('estado_servicio', models.CharField(max_length=100)),
                ('ultima_verificacion', models.DateTimeField(blank=True, null=True)),
                ('instancia', models.ForeignKey(db_column='instancia_id', on_delete=django.db.models.deletion.CASCADE, to='sgbda.instancia')),
            ],
            options={
                'db_table': 'servicio',
            },
        ),
        migrations.CreateModel(
            name='servidor',
            fields=[
                ('id_servidor', models.AutoField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField()),
                ('sistema_operativo', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField()),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, to='sgbda.cliente')),
            ],
            options={
                'db_table': 'servidor',
            },
        ),
        migrations.AddField(
            model_name='instancia',
            name='servidor',
            field=models.ForeignKey(db_column='servidor_id', on_delete=django.db.models.deletion.CASCADE, to='sgbda.servidor'),
        ),
    ]
