# Generated by Django 6.0.5 on 2026-05-15 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='actualizaciones',
            fields=[
                ('id_actualizaciones', models.AutoField(primary_key=True, serialize=False)),
                ('major_version', models.CharField(max_length=50)),
                ('cu', models.CharField(max_length=100)),
                ('kb', models.CharField(max_length=100)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('soportado', models.BooleanField(default=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'actualizaciones',
            },
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Conexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_servidor', models.GenericIPAddressField()),
                ('puerto', models.CharField(max_length=50)),
                ('tipo_autenticacion', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=255)),
                ('password_encriptado', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'conexion',
            },
        ),
        migrations.CreateModel(
            name='instancia',
            fields=[
                ('id_instancia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_instancia', models.CharField(max_length=255)),
                ('puerto', models.CharField(max_length=50)),
                ('major_version', models.CharField(max_length=50)),
                ('edition', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'instancia',
            },
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('rol', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='checkSQL',
            fields=[
                ('id_check', models.AutoField(primary_key=True, serialize=False)),
                ('build_detectado', models.CharField(max_length=100)),
                ('build_referencia', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('fecha_check', models.DateTimeField()),
                ('detalle', models.TextField(blank=True, null=True)),
                ('instancia', models.ForeignKey(db_column='instancia_id', on_delete=django.db.models.deletion.CASCADE, to='sgbda.instancia')),
            ],
            options={
                'db_table': 'check_sql',
            },
        ),
        migrations.CreateModel(
            name='servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=255)),
                ('estado_servicio', models.CharField(max_length=100)),
                ('ultima_verificacion', models.DateTimeField(blank=True, null=True)),
                ('instancia', models.ForeignKey(db_column='instancia_id', on_delete=django.db.models.deletion.CASCADE, to='sgbda.instancia')),
            ],
            options={
                'db_table': 'servicio',
            },
        ),
        migrations.CreateModel(
            name='servidor',
            fields=[
                ('id_servidor', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('hostname', models.CharField(max_length=255)),
                ('sistema_operativo', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, to='sgbda.cliente')),
            ],
            options={
                'db_table': 'servidor',
            },
        ),
        migrations.AddField(
            model_name='instancia',
            name='servidor',
            field=models.ForeignKey(db_column='servidor_id', on_delete=django.db.models.deletion.CASCADE, to='sgbda.servidor'),
        ),
    ]
