# Generated by Django 6.0.5 on 2026-05-18 03:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgbda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualizaciones',
            name='cu',
        ),
        migrations.RemoveField(
            model_name='actualizaciones',
            name='fecha',
        ),
        migrations.AddField(
            model_name='actualizaciones',
            name='build',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actualizaciones',
            name='descripcion',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actualizaciones',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
