# Generated by Django 6.0.5 on 2026-05-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgbda', '0002_remove_actualizaciones_cu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualizaciones',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
