# Generated by Django 6.0.5 on 2026-05-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgbda', '0003_alter_actualizaciones_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualizaciones',
            name='build',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='actualizaciones',
            name='kb',
            field=models.CharField(max_length=150),
        ),
    ]
