# Generated by Django 6.0.5 on 2026-05-20 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgbda', '0004_alter_actualizaciones_build_alter_actualizaciones_kb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='cliente',
            field=models.ForeignKey(blank=True, db_column='cliente_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='sgbda.cliente'),
        ),
    ]
