# Generated by Django 6.0.5 on 2026-05-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgbda', '0005_alter_servidor_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancia',
            name='build',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
