# Generated by Django 6.0.5 on 2026-05-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgbda', '0006_instancia_build'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='tipo_inicio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='ultima_verificacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
