# Generated by Django 6.0.5 on 2026-05-21 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgbda', '0007_servicio_tipo_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='instancia',
            field=models.ForeignKey(db_column='instancia_id', on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='sgbda.instancia'),
        ),
    ]
