# Generated by Django 6.0.5 on 2026-05-22 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgbda', '0008_alter_servicio_instancia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checksql',
            name='instancia',
            field=models.ForeignKey(db_column='instancia_id', on_delete=django.db.models.deletion.CASCADE, related_name='checksql', to='sgbda.instancia'),
        ),
    ]
