# Generated by Django 6.0.5 on 2026-05-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgbda', '0009_alter_checksql_instancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='checksql',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checksql',
            name='nombre_ultima_update',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
