# Generated by Django 6.0.5 on 2026-05-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgbda', '0010_checksql_fecha_publicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checksql',
            name='fecha_publicacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
