# Generated by Django 6.0.5 on 2026-05-25 04:12

import sgbda.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgbda', '0011_alter_checksql_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conexion',
            name='password_encriptado',
            field=sgbda.utils.fields.EncryptedPasswordField(),
        ),
    ]
