# Generated by Django 6.0.5 on 2026-05-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgbda', '0012_alter_conexion_password_encriptado'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancia',
            name='administrado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instancia',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
