# Generated by Django 6.0.5 on 2026-05-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgbda', '0013_instancia_administrado_instancia_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancia',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
    ]
