# Generated by Django 6.0.5 on 2026-05-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgbda', '0014_alter_instancia_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='conexion',
            name='motor',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
