# Generated by Django 6.0.5 on 2026-05-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgbda', '0015_conexion_motor'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualizaciones',
            name='motor',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
