# Generated by Django 6.0.5 on 2026-05-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgbda', '0016_actualizaciones_motor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancia',
            name='build',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
