# Generated by Django 6.0.5 on 2026-05-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgbda', '0017_alter_instancia_build'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancia',
            name='build',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
