# Generated by Django 6.0.5 on 2026-05-29 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgbda', '0018_alter_instancia_build'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualizaciones',
            name='soportado',
        ),
    ]
