# Generated by Django 6.0.5 on 2026-07-09 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgbda', '0019_remove_actualizaciones_soportado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('mantenimiento', 'Mantenimiento mensual'), ('soporte', 'Soporte esporadico')], max_length=20, verbose_name='motivo')),
                ('dia_semana', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miercoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sabado'), (6, 'Domingo')], null=True, verbose_name='dia de la semana')),
                ('posicion_mes', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1°'), (2, '2°'), (3, '3°'), (4, '4°'), (5, '5° (ultimo)')], null=True, verbose_name='posicion en el mes')),
                ('fecha_exacta', models.DateField(blank=True, null=True, verbose_name='fecha exacta')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='sgbda.cliente', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'asignacion',
                'verbose_name_plural': 'asignaciones',
                'db_table': 'asignacion',
                'indexes': [models.Index(fields=['cliente', 'motivo'], name='asignacion_cliente_8f2f2a_idx'), models.Index(fields=['motivo', 'dia_semana', 'posicion_mes'], name='asignacion_motivo_8decdc_idx'), models.Index(fields=['motivo', 'fecha_exacta'], name='asignacion_motivo_b29604_idx')],
            },
        ),
    ]
