# Generated by Django 6.0.5 on 2026-07-10 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgbda', '0020_asignacion'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='asignacion',
            name='asignacion_motivo_8decdc_idx',
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_exacta',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='fecha exacta'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='dia_semana',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='posicion_mes',
        ),
    ]
