# Generated by Django 6.0.5 on 2026-07-30 21:30

import sgbda.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgbda', '0021_remove_asignacion_asignacion_motivo_8decdc_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='conexion_ssh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_servidor', models.GenericIPAddressField()),
                ('usuario', models.CharField(max_length=255)),
                ('password_encriptado', sgbda.utils.fields.EncryptedPasswordField()),
            ],
            options={
                'db_table': 'conexion_ssh',
            },
        ),
    ]
