# Generated by Django 6.0.5 on 2026-08-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgbda', '0022_conexion_ssh'),
    ]

    operations = [
        migrations.AddField(
            model_name='conexion_ssh',
            name='puerto',
            field=models.CharField(default=22, max_length=50),
            preserve_default=False,
        ),
    ]
